from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from Zong_TingChe.Zongoperationpage import OperaPage_Login
from time import sleep
from pywinauto import Desktop
import random



class Service_Member_Zong(OperaPage_Login):

    parkadmin = (By.XPATH,'//div/ul/div[4]/li/div/span')
    servicecar = (By.XPATH,'//div/ul/div[4]/li/ul/div[5]/a/li/span')
    membercar = (By.XPATH,'//section/div/div[1]/ul/li[1]/span')
    #新增会员车服务
    memberadd = (By.XPATH,'//div/div[2]/div[2]/div[1]/div[1]/button/span/span')
    memberadd_park = (By.XPATH,'//form/div[1]/div[1]/div/div/div/div[1]/input')
    memberadd_park_choose = (By.XPATH,'//div[1]/div[1]/ul/li/span[text()="自动化测试车场"]')
    memberadd_vip_name = (By.XPATH,'//form/div[1]/div[2]/div/div/div/div/input')
    memberadd_vip_name_choose = (By.XPATH,'//div[1]/div[1]/ul/li/span[text()="全场会员套餐"]')
    memberadd_car_owner_name = (By.XPATH,'//form/div[2]/div[1]/div/div/div/input')
    memberadd_phone = (By.XPATH,'//form/div[2]/div[2]/div/div/div/input')
    memberadd_plate = (By.XPATH,'//form/div[3]/div/div/div/div/input')
    memberadd_effective = (By.XPATH,'//form/div[4]/div[1]/div/div/div[1]/input')
    memberadd_effective_data = (By.XPATH,'//div[1]/div/div[1]/span[1]/div/input')
    memberadd_effective_time = (By.XPATH,'//div[1]/div/div[1]/span[2]/div[1]/input')
    memberadd_effective_time_confirm = (By.XPATH,'//div/div[1]/span[2]/div[2]/div[2]/button[2]')
    memberadd_effective_confirm = (By.XPATH,'//div[2]/button[2]/span')
    memberadd_cut = (By.XPATH,'//form/div[4]/div[2]/div/div/div/input')
    memberadd_cut_data = (By.XPATH,'//div[1]/div/div[1]/span[1]/div/input')
    memberadd_cut_time = (By.XPATH,'//div[1]/div/div[1]/span[2]/div[1]/input')
    memberadd_cut_time_confirm = (By.XPATH,'//div/div[1]/span[2]/div[2]/div[2]/button[2]')
    memberadd_cut_confirm = (By.XPATH,'//div[2]/button[2]/span')
    memberadd_reality_money = (By.XPATH,'//form/div[5]/div[2]/div/div/div/input')
    memberadd_explain = (By.XPATH,'//form/div[6]/div/div/div/div/textarea')
    memberadd_blank = (By.XPATH,'//div/div[1]/span[text()="新增服务"]')
    memberadd_confirm = (By.XPATH,'//div/div[3]/div/button[1]/span')
    #查询会员车服务
    memberfind_search = (By.XPATH,'//form/div[4]/div/button[1]/span')
    memberfind_reset = (By.XPATH,'//form/div[4]/div/button[2]/span')
    #修改会员车服务
    memberfind_park = (By.XPATH, '//form/div[1]/div/div/div/input')
    memberfind_park_choose = (By.XPATH,'//div[1]/div[1]/ul/li/span[text()="吴忠测试车场"]')
    memberfind_plate = (By.XPATH,'//form/div[2]/div/div/input')
    memberupdate = (By.XPATH,'//table/tbody/tr[1]/td[11]/div/button[2]/span')
    memberupdate_phone = (By.XPATH,'//form/div[2]/div/div/div/input')
    memberupdate_confirm = (By.XPATH,'//div/div[3]/div/button[1]/span')
    #导入会员车服务
    memberimport = (By.XPATH,'//div/div[2]/div[2]/div[1]/div[3]/button/span/span')
    memberimport_park = (By.XPATH,'//form/div[1]/div/div/div[1]/input')
    memberimport_park_choose = (By.XPATH,'//div[1]/div[1]/ul/li[4]/span[text()="自动化测试车场"]')
    memberimport_name = (By.XPATH,'//form/div[2]/div/div/div[1]/input')
    memberimport_name_choose = (By.XPATH,'//div[1]/div[1]/ul/li/span[text()="全场会员套餐"]')
    memberimport_file_choose = (By.XPATH,'//form/div[3]/div/div/div/button/span')
    memberimport_confirm = (By.XPATH,'//div/div[3]/div/button[1]/span')
    #删除会员车服务
    memberdel_choose = (By.XPATH,'//table/thead/tr/th[1]/div/label/span/span')
    memberdel_del = (By.XPATH,'//div/div[2]/div[2]/div[1]/div[2]/button/span/span')
    memberdel_confirm = (By.XPATH,'//div/div[3]/button[2]/span')


    def park_member(self):
        try:
            self.click_script_zong(OperaPage_Login.shrink)
        except:
            pass
        self.click_script_zong(Service_Member_Zong.parkadmin)
        self.click_script_zong(Service_Member_Zong.servicecar)
        self.click_zong(Service_Member_Zong.membercar)

    def login_member(self,head,username,password):
        self.log_zong(head)
        self.login_zonglogin(username,password)
        self.park_member()

    def service_member_add(self,head,username,password,choose,car_owner_name,phone,plate,
                           effective_data_value,effective_time_value,cut_data_value,cut_time_value,reality_money,
                           explain):
        self.login_member(head,username,password)
        self.click_zong(Service_Member_Zong.memberadd)
        self.click_zong(Service_Member_Zong.memberadd_park)
        self.click_eles_presence_zong(Service_Member_Zong.memberadd_park_choose,1)
        if choose == 'one':
            self.click_zong(Service_Member_Zong.memberadd_vip_name)
            self.click_zong(Service_Member_Zong.memberadd_vip_name_choose)
            self.click_zong(Service_Member_Zong.memberadd_effective)
            self.send_key_zong(Service_Member_Zong.memberadd_effective_data,Keys.CONTROL,'a')
            self.send_key_zong(Service_Member_Zong.memberadd_effective_data,Keys.BACK_SPACE)
            self.send_key_zong(Service_Member_Zong.memberadd_effective_data,effective_data_value)
            self.click_zong(Service_Member_Zong.memberadd_effective_time)
            self.send_key_zong(Service_Member_Zong.memberadd_effective_time,Keys.CONTROL,'a')
            self.send_key_zong(Service_Member_Zong.memberadd_effective_time,Keys.BACK_SPACE)
            self.send_key_zong(Service_Member_Zong.memberadd_effective_time,effective_time_value)
            self.click_zong(Service_Member_Zong.memberadd_effective_time_confirm)
            self.click_zong(Service_Member_Zong.memberadd_effective_confirm)
            self.click_zong(Service_Member_Zong.memberadd_cut)
            self.send_keys_presence_zong(Service_Member_Zong.memberadd_cut_data,1,Keys.CONTROL,'a')
            self.send_keys_presence_zong(Service_Member_Zong.memberadd_cut_data,1,Keys.BACK_SPACE)
            self.send_keys_presence_zong(Service_Member_Zong.memberadd_cut_data,1,cut_data_value)
            self.click_eles_presence_zong(Service_Member_Zong.memberadd_cut_time,1)
            self.send_keys_presence_zong(Service_Member_Zong.memberadd_cut_time,1,Keys.CONTROL,'a')
            self.send_keys_presence_zong(Service_Member_Zong.memberadd_cut_time,1,Keys.BACK_SPACE)
            self.send_keys_presence_zong(Service_Member_Zong.memberadd_cut_time,1,cut_time_value)
            self.click_eles_presence_zong(Service_Member_Zong.memberadd_cut_time_confirm,1)
            self.click_eles_presence_zong(Service_Member_Zong.memberadd_cut_confirm,1)
        elif choose == 'two':
            self.click_zong(Service_Member_Zong.memberadd_vip_name)
            self.click_zong(Service_Member_Zong.memberadd_vip_name_choose)
            self.click_zong(Service_Member_Zong.memberadd_cut)
            self.click_zong(Service_Member_Zong.memberadd_cut_time)
            self.send_key_zong(Service_Member_Zong.memberadd_cut_time,Keys.CONTROL,'a')
            self.send_key_zong(Service_Member_Zong.memberadd_cut_time,Keys.BACK_SPACE)
            self.send_key_zong(Service_Member_Zong.memberadd_cut_time,cut_time_value)
            self.click_zong(Service_Member_Zong.memberadd_cut_time_confirm)
            self.send_key_zong(Service_Member_Zong.memberadd_cut_data,Keys.CONTROL,'a')
            self.send_key_zong(Service_Member_Zong.memberadd_cut_data,Keys.BACK_SPACE)
            self.send_key_zong(Service_Member_Zong.memberadd_cut_data,cut_data_value)
            self.click_zong(Service_Member_Zong.memberadd_cut_confirm)
            self.click_zong(Service_Member_Zong.memberadd_effective)
            self.send_keys_presence_zong(Service_Member_Zong.memberadd_effective_data,1,Keys.CONTROL,'a')
            self.send_keys_presence_zong(Service_Member_Zong.memberadd_effective_data,1,Keys.BACK_SPACE)
            self.send_keys_presence_zong(Service_Member_Zong.memberadd_effective_data,1,effective_data_value)
            self.click_eles_presence_zong(Service_Member_Zong.memberadd_effective_time,1)
            self.send_keys_presence_zong(Service_Member_Zong.memberadd_effective_time,1,Keys.CONTROL,'a')
            self.send_keys_presence_zong(Service_Member_Zong.memberadd_effective_time,1,Keys.BACK_SPACE)
            self.send_keys_presence_zong(Service_Member_Zong.memberadd_effective_time,1,effective_time_value)
            self.click_eles_presence_zong(Service_Member_Zong.memberadd_effective_time_confirm,1)
            self.click_eles_presence_zong(Service_Member_Zong.memberadd_effective_confirm,1)
        elif choose == 'three':
            self.click_zong(Service_Member_Zong.memberadd_effective)
            self.send_key_zong(Service_Member_Zong.memberadd_effective_data,Keys.CONTROL,'a')
            self.send_key_zong(Service_Member_Zong.memberadd_effective_data,Keys.BACK_SPACE)
            self.send_key_zong(Service_Member_Zong.memberadd_effective_data,effective_data_value)
            self.click_zong(Service_Member_Zong.memberadd_effective_time)
            self.send_key_zong(Service_Member_Zong.memberadd_effective_time,Keys.CONTROL,'a')
            self.send_key_zong(Service_Member_Zong.memberadd_effective_time,Keys.BACK_SPACE)
            self.send_key_zong(Service_Member_Zong.memberadd_effective_time,effective_time_value)
            self.click_zong(Service_Member_Zong.memberadd_effective_time_confirm)
            self.click_zong(Service_Member_Zong.memberadd_effective_confirm)
            self.click_zong(Service_Member_Zong.memberadd_cut)
            self.send_keys_presence_zong(Service_Member_Zong.memberadd_cut_data,1,Keys.CONTROL,'a')
            self.send_keys_presence_zong(Service_Member_Zong.memberadd_cut_data,1,Keys.BACK_SPACE)
            self.send_keys_presence_zong(Service_Member_Zong.memberadd_cut_data,1,cut_data_value)
            self.click_eles_presence_zong(Service_Member_Zong.memberadd_cut_time,1)
            self.send_keys_presence_zong(Service_Member_Zong.memberadd_cut_time,1,Keys.CONTROL,'a')
            self.send_keys_presence_zong(Service_Member_Zong.memberadd_cut_time,1,Keys.BACK_SPACE)
            self.send_keys_presence_zong(Service_Member_Zong.memberadd_cut_time,1,cut_time_value)
            self.click_eles_presence_zong(Service_Member_Zong.memberadd_cut_time_confirm,1)
            self.click_eles_presence_zong(Service_Member_Zong.memberadd_cut_confirm,1)
        elif choose == 'four':
            self.click_zong(Service_Member_Zong.memberadd_cut)
            self.send_key_zong(Service_Member_Zong.memberadd_cut_data,Keys.CONTROL,'a')
            self.send_key_zong(Service_Member_Zong.memberadd_cut_data,Keys.BACK_SPACE)
            self.send_key_zong(Service_Member_Zong.memberadd_cut_data,cut_data_value)
            self.click_zong(Service_Member_Zong.memberadd_cut_time)
            self.send_key_zong(Service_Member_Zong.memberadd_cut_time,Keys.CONTROL,'a')
            self.send_key_zong(Service_Member_Zong.memberadd_cut_time,Keys.BACK_SPACE)
            self.send_key_zong(Service_Member_Zong.memberadd_cut_time,cut_time_value)
            self.click_zong(Service_Member_Zong.memberadd_cut_time_confirm)
            self.click_zong(Service_Member_Zong.memberadd_cut_confirm)
        elif choose == 'five':
            self.click_zong(Service_Member_Zong.memberadd_effective)
            self.send_key_zong(Service_Member_Zong.memberadd_effective_data,Keys.CONTROL,'a')
            self.send_key_zong(Service_Member_Zong.memberadd_effective_data,Keys.BACK_SPACE)
            self.send_key_zong(Service_Member_Zong.memberadd_effective_data,effective_data_value)
            self.click_zong(Service_Member_Zong.memberadd_effective_time)
            self.send_key_zong(Service_Member_Zong.memberadd_effective_time,Keys.CONTROL,'a')
            self.send_key_zong(Service_Member_Zong.memberadd_effective_time,Keys.BACK_SPACE)
            self.send_key_zong(Service_Member_Zong.memberadd_effective_time,effective_time_value)
            self.click_zong(Service_Member_Zong.memberadd_effective_time_confirm)
            self.click_zong(Service_Member_Zong.memberadd_effective_confirm)
        self.send_key_zong(Service_Member_Zong.memberadd_car_owner_name,car_owner_name)
        self.send_key_zong(Service_Member_Zong.memberadd_phone,phone)
        self.send_key_zong(Service_Member_Zong.memberadd_plate,plate)
        self.send_key_zong(Service_Member_Zong.memberadd_reality_money,reality_money)
        self.send_key_zong(Service_Member_Zong.memberadd_explain,explain)
        self.click_eles_presence_zong(Service_Member_Zong.memberadd_blank,-1)
        self.click_zong(Service_Member_Zong.memberadd_confirm)

    def service_member_update(self,head,username,password,plate,phone):
        self.login_member(head,username,password)
        self.click_zong(Service_Member_Zong.memberfind_park)
        self.click_eles_presence_zong(Service_Member_Zong.memberfind_park_choose,-1)
        self.send_key_zong(Service_Member_Zong.memberfind_plate,plate)
        self.click_zong(Service_Member_Zong.memberfind_search)
        self.click_zong(Service_Member_Zong.memberupdate)
        self.send_key_zong(Service_Member_Zong.memberupdate_phone,Keys.CONTROL,'a')
        self.send_key_zong(Service_Member_Zong.memberupdate_phone,Keys.BACK_SPACE)
        self.send_key_zong(Service_Member_Zong.memberupdate_phone,phone)
        sleep(2)
        self.click_eles_presence_zong(Service_Member_Zong.memberupdate_confirm,-1)

    def service_member_find_search(self,head,username,password,ele,values):
        self.login_member(head,username,password)
        self.click_zong(Service_Member_Zong.memberfind_park)
        self.click_eles_presence_zong(Service_Member_Zong.memberfind_park_choose,-1)
        service_member_redact = (By.XPATH,ele)
        self.send_key_zong(service_member_redact,values)
        self.click_zong(Service_Member_Zong.memberfind_search)

    def service_member_find_reset(self):
        self.click_zong(Service_Member_Zong.memberfind_reset)
        self.click_zong(Service_Member_Zong.memberfind_park)
        self.click_eles_presence_zong(Service_Member_Zong.memberfind_park_choose,-1)
        self.click_zong(Service_Member_Zong.memberfind_search)
        sleep(2)

    def service_member_import(self,head,username,password):
        self.login_member(head,username,password)
        self.click_zong(Service_Member_Zong.memberimport)
        self.click_eles_presence_zong(Service_Member_Zong.memberimport_park,-1)
        self.click_eles_presence_zong(Service_Member_Zong.memberimport_park_choose,-1)
        self.click_zong(Service_Member_Zong.memberimport_name)
        self.click_eles_presence_zong(Service_Member_Zong.memberimport_name_choose,-1)
        self.click_zong(Service_Member_Zong.memberimport_file_choose)
        app = Desktop()
        dig = app["打开"]
        dig["文件名(&N):Edit1"].type_keys(r"F:\servicemember.xlsx")
        dig["打开(&O)"].click()
        sleep(1)
        self.click_zong(Service_Member_Zong.memberimport_confirm)

    def service_member_del(self,head,username,password):
        self.login_member(head,username,password)
        self.click_zong(Service_Member_Zong.memberfind_park)
        self.click_eles_presence_zong(Service_Member_Zong.memberfind_park_choose,-1)
        self.click_zong(Service_Member_Zong.memberfind_search)
        self.click_zong(Service_Member_Zong.memberdel_choose)
        self.click_zong(Service_Member_Zong.memberdel_del)
        self.click_zong(Service_Member_Zong.memberdel_confirm)
