
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from time import sleep

driver = webdriver.Chrome()
driver.get('https://test.ghparking.com/')
driver.maximize_window()
driver.implicitly_wait(10)
driver.find_element_by_name('username').send_keys('13112345678')
driver.find_element_by_name('password').send_keys('123456')
driver.find_element_by_xpath('//*[@id="app"]/div/form/button/span').click()
sleep(8)
driver.find_element_by_xpath('//div[1]/div[2]/div[1]/div/ul/div[3]/li/div/span').click()
sleep(1)
driver.find_element_by_xpath('//div/div[1]/div[2]/div[1]/div/ul/div[3]/li/ul/div[1]/a/li/span').click()
sleep(1)
driver.find_element_by_xpath('//div/div[2]/div/div[1]/div/button/span').click()
sleep(1)
driver.find_element_by_xpath('//div/div[5]/div[1]/div/div[2]/form/div[1]/div[1]/div/div/div/input').send_keys('111')
sleep(1)
driver.find_element_by_xpath('//div/div[5]/div[1]/div/div[2]/form/div[1]/div[2]/div/div/div/div[1]/div[1]/div[2]'
                             '/input').send_keys(Keys.DOWN,Keys.DOWN,Keys.RIGHT,Keys.DOWN,Keys.DOWN,Keys.RIGHT,Keys.DOWN,Keys.DOWN,Keys.ENTER)
sleep(1)
driver.find_element_by_xpath('//div/div[5]/div[1]/div/div[2]/form/div[2]/div[1]/div/div/div/input').send_keys('张三')
sleep(1)
driver.find_element_by_xpath('//div/div[5]/div[1]/div/div[2]/form/div[2]/div[2]/div/div/div/input').send_keys('15312341234')
sleep(1)
driver.find_element_by_xpath('//div/div[5]/div[1]/div/div[2]/form/div[3]/div/div/div/div/input').send_keys('1234@123.com')
sleep(1)
driver.find_element_by_xpath('//div/div[5]/div[1]/div/div[2]/form/div[4]/div/div/div/input').send_keys('1234')
sleep(1)
driver.find_element_by_xpath('//div/div[5]/div[1]/div/div[3]/div/button[1]/span').click()
sleep(2)
driver.find_element_by_xpath('//div/div[5]/div[2]/div/div[2]/form/div[2]/div[1]/div/div/div[1]/input').click()
sleep(1)
driver.find_element_by_xpath('//div[1]/div/div[1]/span[1]/div/input').send_keys('2021-05-01')
sleep(1)
driver.find_element_by_xpath('//div[1]/div/div[1]/span[2]/div[1]/input').send_keys('12:00:00')
sleep(1)
driver.find_element_by_xpath('//div[2]/button[2]/span').click()
sleep(1)
driver.find_element_by_xpath('//div/div[5]/div[2]/div/div[2]/form/div[2]/div[2]/div/div/div[1]/input').click()
sleep(1)
ele1 = driver.find_elements_by_xpath('//div[1]/div/div[1]/span[1]/div/input')
ele1[1].send_keys('2021-06-01')
sleep(1)
ele = driver.find_elements_by_xpath('//div[1]/div/div[1]/span[2]/div[1]/input')
ele[1].click()
sleep(1)
ele[1].clear()
sleep(1)
ele[1].send_keys('12:00:00')
